check whether a customer will leave the bank

In [24]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Importing the dataset
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values



In [25]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [26]:
org_data=X[1]
org_data

array([608, 'Spain', 'Female', 41, 1, 83807.86, 1, 0, 1, 112542.58],
      dtype=object)

In [27]:
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

In [28]:
# Encoding categorical data

from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])
onehotencoder = OneHotEncoder(categorical_features = [1])
X = onehotencoder.fit_transform(X).toarray()
X = X[:, 1:]

# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [29]:
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

In [30]:
X

array([[0.0000000e+00, 0.0000000e+00, 6.1900000e+02, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [0.0000000e+00, 1.0000000e+00, 6.0800000e+02, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [0.0000000e+00, 0.0000000e+00, 5.0200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [0.0000000e+00, 0.0000000e+00, 7.0900000e+02, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [1.0000000e+00, 0.0000000e+00, 7.7200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [0.0000000e+00, 0.0000000e+00, 7.9200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [31]:
Encoded_data=X[1]
Encoded_data

array([0.0000000e+00, 1.0000000e+00, 6.0800000e+02, 0.0000000e+00,
       4.1000000e+01, 1.0000000e+00, 8.3807860e+04, 1.0000000e+00,
       0.0000000e+00, 1.0000000e+00, 1.1254258e+05])

In [32]:
X_train

array([[-0.5698444 ,  1.74309049,  0.16958176, ...,  0.64259497,
        -1.03227043,  1.10643166],
       [ 1.75486502, -0.57369368, -2.30455945, ...,  0.64259497,
         0.9687384 , -0.74866447],
       [-0.5698444 , -0.57369368, -1.19119591, ...,  0.64259497,
        -1.03227043,  1.48533467],
       ...,
       [-0.5698444 , -0.57369368,  0.9015152 , ...,  0.64259497,
        -1.03227043,  1.41231994],
       [-0.5698444 ,  1.74309049, -0.62420521, ...,  0.64259497,
         0.9687384 ,  0.84432121],
       [ 1.75486502, -0.57369368, -0.28401079, ...,  0.64259497,
        -1.03227043,  0.32472465]])

In [33]:
X_test

array([[ 1.75486502, -0.57369368, -0.55204276, ...,  0.64259497,
         0.9687384 ,  1.61085707],
       [-0.5698444 , -0.57369368, -1.31490297, ...,  0.64259497,
        -1.03227043,  0.49587037],
       [-0.5698444 ,  1.74309049,  0.57162971, ...,  0.64259497,
         0.9687384 , -0.42478674],
       ...,
       [-0.5698444 ,  1.74309049, -0.74791227, ...,  0.64259497,
        -1.03227043,  0.71888467],
       [ 1.75486502, -0.57369368, -0.00566991, ...,  0.64259497,
         0.9687384 , -1.54507805],
       [ 1.75486502, -0.57369368, -0.79945688, ...,  0.64259497,
        -1.03227043,  1.61255917]])

In [34]:
y_train

array([0, 0, 0, ..., 0, 0, 1], dtype=int64)

In [35]:
y_test

array([0, 1, 0, ..., 0, 0, 0], dtype=int64)

In [36]:
# Part 2 - Now let's make the ANN!

# Importing the Keras libraries and packages
import keras
from keras.models import Sequential
from keras.layers import Dense

# Initialising the ANN
classifier = Sequential()

# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))

# Adding the second hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Fitting the ANN to the Training set
classifier.fit(X_train, y_train, batch_size = 10, epochs = 100)



Epoch 1/100
8000/8000 [==============================] - 1s 136us/step - loss: 0.4884 - acc: 0.7957
Epoch 2/100
8000/8000 [==============================] - 1s 93us/step - loss: 0.4300 - acc: 0.7960
Epoch 3/100
8000/8000 [==============================] - 1s 92us/step - loss: 0.4267 - acc: 0.7987
Epoch 4/100
8000/8000 [==============================] - 1s 93us/step - loss: 0.4202 - acc: 0.8220
Epoch 5/100
8000/8000 [==============================] - 1s 94us/step - loss: 0.4136 - acc: 0.8275
Epoch 6/100
8000/8000 [==============================] - 1s 93us/step - loss: 0.4100 - acc: 0.8325
Epoch 7/100
8000/8000 [==============================] - 1s 94us/step - loss: 0.4071 - acc: 0.8316
Epoch 8/100
8000/8000 [==============================] - 1s 94us/step - loss: 0.4053 - acc: 0.8335
Epoch 9/100
8000/8000 [==============================] - 1s 95us/step - loss: 0.4040 - acc: 0.8346
Epoch 10/100
8000/8000 [==============================] - 1s 95us/step - loss: 0.4032 - acc: 0.8347
Epoch 11

8000/8000 [==============================] - 1s 97us/step - loss: 0.3372 - acc: 0.8615
Epoch 83/100
8000/8000 [==============================] - 1s 91us/step - loss: 0.3372 - acc: 0.8617
Epoch 84/100
8000/8000 [==============================] - 1s 94us/step - loss: 0.3372 - acc: 0.8607
Epoch 85/100
8000/8000 [==============================] - 1s 90us/step - loss: 0.3368 - acc: 0.8635
Epoch 86/100
8000/8000 [==============================] - 1s 90us/step - loss: 0.3363 - acc: 0.8626
Epoch 87/100
8000/8000 [==============================] - 1s 90us/step - loss: 0.3369 - acc: 0.8620
Epoch 88/100
8000/8000 [==============================] - 1s 89us/step - loss: 0.3366 - acc: 0.8612
Epoch 89/100
8000/8000 [==============================] - 1s 88us/step - loss: 0.3361 - acc: 0.8642
Epoch 90/100
8000/8000 [==============================] - 1s 88us/step - loss: 0.3366 - acc: 0.8622
Epoch 91/100
8000/8000 [==============================] - 1s 87us/step - loss: 0.3366 - acc: 0.8626
Epoch 92/100


In [37]:
# Part 3 - Making predictions and evaluating the model

# Predicting the Test set results
y_pred = classifier.predict(X_test)



In [13]:
y_pred

array([[0.2335441 ],
       [0.31441164],
       [0.18123636],
       ...,
       [0.19054785],
       [0.18393268],
       [0.11150114]], dtype=float32)

In [14]:
y_pred = (y_pred > 0.5)

In [15]:
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [16]:

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [17]:
cm

array([[1532,   63],
       [ 252,  153]], dtype=int64)

Use our ANN model to predict if the customer with the following informations will leave the bank: 

Geography: Spain
Credit Score: 600
Gender: Male
Age: 40 years old
Tenure: 3 years
Balance: $60000
Number of Products: 2
Does this customer have a credit card ? Yes
Is this customer an Active Member: Yes
Estimated Salary: $50000

In [42]:
dataset.iloc[:, 3:13].values[1]

array([608, 'Spain', 'Female', 41, 1, 83807.86, 1, 0, 1, 112542.58],
      dtype=object)

In [39]:
Encoded_data

array([0.0000000e+00, 1.0000000e+00, 6.0800000e+02, 0.0000000e+00,
       4.1000000e+01, 1.0000000e+00, 8.3807860e+04, 1.0000000e+00,
       0.0000000e+00, 1.0000000e+00, 1.1254258e+05])

In [49]:
new_customer = classifier.predict(sc.transform(np.array([[0.0,0.0,600,1,40,3,60000,2,1,1,50000]])))

In [50]:
new_customer = (new_customer > 0.5)
new_customer

array([[False]])